ALTER TABLE "Part" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Part" ADD COLUMN IF NOT EXISTS "partType" TEXT;
ALTER TABLE "Part" ADD COLUMN IF NOT EXISTS "familyPlan" TEXT;
ALTER TABLE "Part" ADD COLUMN IF NOT EXISTS "drawingKey" TEXT;
ALTER TABLE "Part" ADD COLUMN IF NOT EXISTS "drawingName" TEXT;
