DO $$ BEGIN
  CREATE TYPE "CompanyAppearance" AS ENUM ('DARK', 'FLOOR');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "slogan" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "logoKey" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "appearance" "CompanyAppearance" NOT NULL DEFAULT 'DARK';
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "alarmSoundEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "criticalScreenEnabled" BOOLEAN NOT NULL DEFAULT true;
